base_folder: "J:\\projects"
gitignore:
  - '###> darkanakin41/project-generator'
  - '.idea'
  - '###< darkanakin41/project-generator'

project_type:
  default:
    folder: 'idea'
    exec: 'code'
  gfi:
    folder: 'GFI'
    exec: 'idea'
    git:
      user:
        email: 'pierre.lejeune@gfi.fr'
  php:
    folder: 'web'
    exec: 'idea'
  python:
    folder: 'python'
    exec: 'idea'
    gitignore_template: 'Python' # see https://github.com/github/gitignore
    templates:
      default: "python\\default"

vcs:
  github_perso:
    type: "github"
    base_url: "https://github.com"
    user: "darkanakin41"
    token: "af800811252ca7f5267dfb01c760da6d7fab4bd8"